### ISSUE TITLE
find a better name for the iproute2 crate

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#1]
From [/u/zokier on reddit](https://www.reddit.com/r/rust/comments/8yduqa/announcing_a_netlink_crates/e2aajmx), this is confusing and can be perceived as hostile, so let's change the name. Ideas welcome.

**Comment by lu-zero** [comment]
It isn't that confusing, but you could call it `nl.rs` or `rnl` and `rnl-tools` but then searching for it would be a bit more problematic.

I would keep the name as-is, though :)

**Comment by Phlogistique** [comment]
How about "linux-network-config".

Makes it obvious that it accesses the configuration of Linux's network stack.

**Comment by little-dude** [comment]
I ended up renaming it after the protocol itself: `rtnetlink`.
