### ISSUE TITLE
Migrate to tokio 0.3 / mio 0.7

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#105]
Tokio 0.3 has been released and uses mio 0.7

**Comment by little-dude** [comment]
Seems like porting `netlink-sys` is going to be easy: https://discordapp.com/channels/500028886025895936/627986131702644744/779763174437027870

We can just use [`AsyncFd`](https://docs.rs/tokio/0.3.4/tokio/io/unix/struct.AsyncFd.html) which was added in 0.3.2.

**Comment by faern** [comment]
Tokio 1.0 is out and it probably only makes sense to upgrade directly to that and skip 0.3 entirely.
