### ISSUE TITLE
Move to Github Actions

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#106]
Travis jobs take ages to start, and I find Github Actions easier to maintain.

**Comment by JohnTitor** [comment]
One minor issue is that GHA doesn't support "allow-failures" currently, we could just ignore nightly's failure though. If you think it's okay, I'm happy to help the migration :)

**Comment by little-dude** [comment]
So the reason for "allow-failures" originally was that travis would sometimes fail to install clippy or rustfmt. I think this does not happen as often so it should not be a problem.

**Comment by little-dude** [comment]
I also noticed that there are tons of clippy warnings... Probably because we  allow nightly failures actually. I'm fixing them now
