### ISSUE TITLE
Adding VXLAN Support

### ISSUE THREAD

**Issue by gabrik** [little-dude/netlink#113]
Hi, 

First, thank you for this very useful crate.

I noticed that in `rtnetlink` only some types of interfaces can be created.
And I also see that the VxLAN info is not yet defined: https://github.com/little-dude/netlink/blob/e9ece979dc134fc0080c84f1fcf34a730a3a52bd/netlink-packet-route/src/rtnl/link/nlas/link_infos.rs#L215 

As this is very interesting for me to have if you can point me to some references I can try to add it and do a PR with the code.

Should I follow libnl for the definition of the attributes? https://www.infradead.org/~tgr/libnl/doc/api/vxlan_8c_source.html 

Thanks

**Comment by little-dude** [comment]
Hey, thanks a lot for taking a stab at this!
I think `libnl` is indeed a good source. The netlink go library seems to also support vxlan attributes, so you may look there as well, if you want: https://github.com/vishvananda/netlink/blob/d40f9887b852ec4ce633f2a46734422c87fc8336/link_linux.go#L904

**Comment by gabrik** [comment]
This is was implemented by #114, I'm closing this issue
