### ISSUE TITLE
Tag a new release of netlink-packet-route

### ISSUE THREAD

**Issue by ffmancera** [little-dude/netlink#119]
Hello!

Nispor requires IPoIB support which has been implemented on #102. A new release would allow us to use it from Nispor, thank you!

**Comment by cathay4t** [comment]
@little-dude Could you tag a new release?

**Comment by little-dude** [comment]
Hi @ffmancera and @cathay4t,

Sorry very busy week. I'll try to do it tomorrow or Friday.

**Comment by ffmancera** [comment]
@little-dude Sure, no worries! Thank you! :-)

**Comment by little-dude** [comment]
0.6 released :)
