### ISSUE TITLE
printing names of messages without full contents

### ISSUE THREAD

**Issue by mcr** [little-dude/netlink#120]
I have a loop where I'm processing some things from netlink:

````
        while let Some((message, _)) = messages.next().await {
            let payload = message.payload;
            match payload {
                InnerMessage(NewLink(stuff)) => {
                    dump_link_info(stuff);
                }
                _ => { println!("generic message type: {} skipped", payload.message_type()); }
            }
        }

````

If I {:?} print "payload", I get a full, deep decode of the message.  Which is cool, and I will probably want that, but for now I mostly just want to know what I'm missing.  If I print it like above, then I get the numeric message type that I'm skipping.
I'd like to get "InnerMessage(DelRoute(RouteMessage))" or some such, but not the whole thing.
I think that I'd have to implement strings of some kind of each message type; or maybe it's possible to derive Display?

**Comment by little-dude** [comment]
Hey @mcr,

Indeed I haven't implemented `Display` on `NetlinkPayload`. I don't know if you we can _derive_ it though because it looks like this:

```rust
#[derive(Debug, PartialEq, Eq, Clone)]
pub enum NetlinkPayload<I>
where
    I: Debug + PartialEq + Eq + Clone,
{
    Done,
    Error(ErrorMessage),
    Ack(AckMessage),
    Noop,
    Overrun(Vec<u8>),
    InnerMessage(I),
}
```

Deriving `Display` would require `I: Display` and don't want to add this trait bound. However, we could implement it manually.

**Comment by mcr** [comment]
I can live with something manual.

**Comment by stbuehler** [comment]
There is a difference between requiring `I: Display` for all instances or just for the `Display` implementation; you could drop all trait requirements for `I`, and `#[derive(..)]` would implement the derived traits conditional on whether `I` implements them too.

**Comment by little-dude** [comment]
I'm going to close this since there has been no update for a while, and because I don't think there's a clear path forward.
