### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by mxpv** [little-dude/netlink#142]
I'd like to get this crate in kata-containers project (https://github.com/kata-containers/kata-containers/pull/1297), would it be possible to make a new release after https://github.com/little-dude/netlink/pull/134 https://github.com/little-dude/netlink/pull/135 https://github.com/little-dude/netlink/pull/140 ? Those do backward incompatible API changes and deserve a release. Thanks in advance.

**Comment by little-dude** [comment]
Working on it.

**Comment by little-dude** [comment]
Done!

**Comment by mxpv** [comment]
Thanks a lot!
