### ISSUE TITLE
LinkGetRequest never returns any links in new network namespace

### ISSUE THREAD

**Issue by jamesmcm** [little-dude/netlink#145]
Hi,

I'm trying to use the rtnetlink crate in [libvopono](https://github.com/jamesmcm/libvopono) to handle what are currently `ip addr` and `ip link` calls inside the created network namespaces in [vopono](https://github.com/jamesmcm/vopono).

Specifically I want to do the equivalent of:

```bash
ip netns exec netns ip addr add 127.0.0.1/8 dev lo
ip netns exec netns ip link set lo up
```
in the new network namespace.

I followed [this example code](https://github.com/little-dude/netlink/blob/master/rtnetlink/examples/add_address.rs), to write the following code (in a closure running on a new process inside the created network namespace):

https://github.com/jamesmcm/libvopono/blob/master/src/lib.rs#L136-L180

```rust
    /// Create loopback and set up
    /// Equivalent of:
    /// ip netns exec netns ip addr add 127.0.0.1/8 dev lo
    /// ip netns exec netns ip link set lo up
    pub fn add_loopback(&mut self) {
        self.run_in_namespace(
            || {
                let mut rt =
                    tokio::runtime::Runtime::new().expect("Failed to construct Tokio runtime");
                let x = rt.block_on(async {
                    let (connection, handle, _) = rtnetlink::new_connection().unwrap();


                    // Debug code: test if we ever get any links returned
                    let mut links = handle.link().get().execute();
                    println!("async closure runs but links are None");
                    while let Some(l) = links.try_next().await.expect("fail link") {
                        println!("{:?}", l);
                    }
                    // End debug code


                    let mut links = handle
                        .link()
                        .get()
                        .set_name_filter("lo".to_string())
                        .execute();
                    let ip = ipnetwork::IpNetwork::new(
                        std::net::IpAddr::V4(std::net::Ipv4Addr::new(127, 0, 0, 1)),
                        8,
                    )
                    .expect("Failed to construct IP");
                    if let Some(link) = links.try_next().await.expect("Failed to get link") {
                        handle
                            .address()
                            .add(link.header.index, ip.ip(), ip.prefix())
                            .execute()
                            .await
                            .expect("Failed to add address");


                        println!("ip: {:?}", ip);
                        std::thread::sleep(std::time::Duration::from_secs(2));
                        handle
                            .link()
                            .set(link.header.index)
                            .up()
                            .execute()
                            .await
                            .expect("Failed to set link up");
                    }
                });
```

This is then called with this code:

https://github.com/jamesmcm/libvopono/blob/master/src/bin.rs#L4-L12

```rust
    // Create netns
    let mut netns = RawNetworkNamespace::new("testlobin");
    // ip addr before
    let handle = netns.exec_no_block(&["ip", "addr"], false);
    std::thread::sleep(std::time::Duration::from_secs(2));
    kill(handle, SIGKILL).expect("kill failed");
 
    netns.add_loopback();
    std::thread::sleep(std::time::Duration::from_secs(5));
    // ip addr after
    let handle = netns.exec_no_block(&["ip", "addr"], false);
    std::thread::sleep(std::time::Duration::from_secs(2));
```

Giving the following output:

```
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
async closure runs but links are None
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

Note the address is not added and the link is not set UP. It seems the LinkGetRequest only ever returns `None` (even without filtering the links by name) so the requests are never made.

Is there any reason why LinkGetRequest would "fail" like this in a new network namespace?

**Comment by little-dude** [comment]
Hello!

Thanks for taking the time to write a detailed issue. Would you mind also specifying what version of the netlink crates you're using? Also, running the program with `strace` or capturing the netlink packets with `nlmon` as explained [in this blog](https://jvns.ca/blog/2017/09/03/debugging-netlink-requests/) may be useful.

> Is there any reason why LinkGetRequest would "fail" like this in a new network namespace?it.

Yes:

- namespace support has been implemented very recently
- handling namespaces is tricky as you can tell from [this issue](https://github.com/little-dude/netlink/issues/38)

I don't have an answer for you atm but I'll try to reproduce and do some debugging. Let's also ping @gabrik who implemented the namespace support. He may have an idea.

**Comment by little-dude** [comment]
Oh btw, nice summary you've wrote here: https://github.com/jamesmcm/vopono/issues/49 :)

**Comment by jamesmcm** [comment]
Thanks! Here is the strace output btw: https://gist.github.com/jamesmcm/68be8101c0a6cbe6f45a3e56fc6a903e

From `sudo -E strace -s 256 -f -o out -x ./createns`

I'll try out `nlmon` too.

That issue regarding namespaces is really useful, I'll try running strace on `ip netns exec netns ip addr add 127.0.0.1/8 dev lo` too for a comparison.

For my namespace creation I use the bind mount trick to keep it open, etc. as mentioned (mainly because I'd eventually want to support spawning multiple processes in the same network namespace) and it does show up as a namespace afterwards.

The part of forking, moving the forked process to the namespace and then running the closure is quite complicated though (especially when we also have to spawn a Tokio runtime inside the closure!).

**Comment by jamesmcm** [comment]
Fixed by the way, the network namespace part was all fine, in the end it was just the call to `rt.spawn(connection);` missing :man_facepalming: 

See https://github.com/jamesmcm/libvopono/commit/460aa4ae244b7f34d0b6ff359d0231951f484183

Incidentally, it'd be nice to have a synchronous form (maybe feature-gated) of the crate that didn't depend on Tokio / async runtimes, a bit like Rusoto used to do. I'm not sure how much extra work this would be given the current connection setup though.

**Comment by little-dude** [comment]
Glad that the issue was solved.

> Incidentally, it'd be nice to have a synchronous form (maybe feature-gated) of the crate that didn't depend on Tokio / async runtimes, a bit like Rusoto used to do

It's a good idea. It may be possible. Most of the logic in `rtnetlink` consists in building the messages. We could maybe have a synchronous `Connection` object. Feel free to open an issue.

> Thanks for the easy-to-use high-level crate though!

Glad you like it :)
