### ISSUE TITLE
Is it possible/how would I configure an IP address without using tokio?

### ISSUE THREAD

**Issue by rednexela1941** [little-dude/netlink#158]
partially a note to self for later (feel free to close), unless you know off the top of your head / have an example. My project has it's own event loop, so looking to embed the rtnetlink stuff inside of there without causing massive changes + additional (tokio) dependencies.

**Comment by little-dude** [comment]
If you're using `rtnetlink` no, because it's based on `netlink-proto` which uses tokio. But you can use `netlink-sys` and `netlink-packet-route` directly.

I hope that some day we can have a `netlink-proto` crate that is runtime agnostic. But I don't have time to work on this atm.

**Comment by gabrik** [comment]
Well actually it is runtime agnostic, you just need to configure the features, but indeed it needs an async runtime.

**Comment by rednexela1941** [comment]
Cool, thanks guys!
