### ISSUE TITLE
Maintenance and crates.io access

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#161]
Hello,

I haven't had time to correctly maintain these crates lately. This may change in future, since my current employer may start using these crates, and I may be able to get some time to work on them :crossed_fingers:.

In the meantime, are there people willing to help with the releases? I'm currently the only one with crates.io credentials but I have not time to dedicate to this at the moment.

cc @Tim-Zhang @cathay4t @JohnTitor @gabrik

**Comment by JohnTitor** [comment]
I'm happy to help it, we'll make a new release once all the TODOs in #149 are done, right?

**Comment by Tim-Zhang** [comment]
@little-dude I'm willing to help it too, anyway @little-dude @JohnTitor @cathay4t  we should advance this project and release the new version ASAP.  thank you.

**Comment by benjumanji** [comment]
@little-dude thanks for all the work you put into this crate to get it off the ground. I do rely on this crate for some projects of mine and I'd be happy to help push along releases etc.

**Comment by little-dude** [comment]
@Tim-Zhang  @benjumanji can you send me you crates.io usernames, so that I add you to as owner to the netlink crates?

**Comment by little-dude** [comment]
also @cathay4t if you want

**Comment by benjumanji** [comment]
@little-dude my crates user name is this github account, @benjumanji. Thanks!

**Comment by little-dude** [comment]
@benjumanji you should now have invites for:

- https://crates.io/crates/audit
- https://crates.io/crates/rtnetlink
- https://crates.io/crates/netlink-packet-route
- https://crates.io/crates/netlink-packet-core
- https://crates.io/crates/netlink-proto
- https://crates.io/crates/netlink-sys
- https://crates.io/crates/netlink-packet-utils
- https://crates.io/crates/netlink-packet-audit
- https://crates.io/crates/netlink-packet-sock-diag

Please let me know if I have forgotten anything.

**Comment by little-dude** [comment]
@JohnTitor @cathay4t @Tim-Zhang please send me you crates.io handle if you want to have write access as well. I think it's better if at least two active contributors have access.

**Comment by JohnTitor** [comment]
@little-dude I'd like; this is my account: https://crates.io/users/JohnTitor

**Comment by little-dude** [comment]
Done :)

**Comment by Tim-Zhang** [comment]
@little-dude My crates.io account is Tim-Zhang, https://crates.io/users/Tim-Zhang, thanks.

**Comment by cathay4t** [comment]
@little-dude My crates.io account is cathay4t https://crates.io/users/cathay4t

**Comment by little-dude** [comment]
I believe this can be closed now. Thank you everyone!
