### ISSUE TITLE
MalformedNlaValue error

### ISSUE THREAD

**Issue by glebpom** [little-dude/netlink#3]
Hi,

Thanks for the great work!

I've received the `MalformedNlaValue` on the example case 
```
handle.link().get().execute().and_then(|links| {
            println!("{:#?}", links);
            Ok(())
 });
```

The reason is that the size doesn't match in `NativeNla` `from_bytes` check [here](https://github.com/little-dude/netlink/blob/master/rtnetlink/src/packets/nla.rs#L257)
I was getting this error on `LinkStats<u32>` (92 bytes vs. required 96 bytes). 

It seems like, structs may have the different size depending on the Linux version (?).

**Comment by little-dude** [comment]
Hi!

I was afraid this kind of issue would happen... I hope we won't end up  with too much conditional compilation based on the kernel version.

May I ask which kernel you're using? 

Cheers,
Corentin

**Comment by little-dude** [comment]
Also if you have a capture of the faulty packets, that might help.

**Comment by glebpom** [comment]
```
docker-user@gce2:~$ uname -a
Linux gce2 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I'm afraid conditional compilation will not work because there is no kernel version information during the compilation.

I had a brief look on the structures, containing the link information in the Linux kernel (containing the fields from `LinkStats` rust structure). It seems like there are a lot of them, which look "truncated" (missing fields at the end). It probably means that buffers with less size are normal, we should just copy all bytes, and initialize missing fields with zeroes.

**Comment by glebpom** [comment]
It could be something like:

```
pub(crate) trait NativeNla
where
    Self: Copy,
{
    fn from_bytes(buf: &[u8]) -> Result<Self> {
        if buf.len() > size_of::<Self>() {
            error!("Size mismatch {} > {}", buf.len(), size_of::<Self>());
            return Err(Error::MalformedNlaValue);
        }
        let mut new_buf = vec![0u8; size_of::<Self>()];
        new_buf[..buf.len()].copy_from_slice(buf);

        Ok(unsafe { ptr::read(new_buf.as_ptr() as *const Self) })
    }
```

**Comment by little-dude** [comment]
@glebpom just to let you know that I won't be able to work on that until mid-Septembre unfortunately. I'm planning to fix that after I finish a big refactoring to provide an audit library (cf https://github.com/little-dude/netlink/pull/2).
