### ISSUE TITLE
Split netlink-packet into smaller crates

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#35]
As [suggested by @flier](https://github.com/little-dude/netlink/pull/32#issuecomment-459595419) it may be a good idea to split `netlink-packet` into smaller crates for each netlink protocol (at the moment: audit, route, and sock_diag). Then, `netlink-packet` would just expose a generic `NetlinkMessage` type.

~~I'm not 100% sure I want to do this though. The main reason would be that `netlink-packet` is getting big, maybe to big. But is that a good enough reason? Are there other reasons I'm not seeing?~~

~~I also see one downside: there is some stuff that could (and probably should) be re-used for all these new crates: error types, traits (`Parseable`, `Emitable`, etc.), code related to the netlink attributes (aka NLAs). That means we'll have another crate, that contains this boilerplate as a dependency of all the new crates. That seems like to much fragmentation to me.~~

~~But if we chose to do that, remains the question of naming these crates: I'd like to have a common prefix to indicate that they all provide netlink messages. Something like: `netlink-packet-route`, `netlink-packet-audit`, `netlink-packet-sock-diag` (and `netlink-packet-common` for the crate that contains the common code)?~~

Edit: I had not fully understood what @flier meant. See [this comment](https://github.com/little-dude/netlink/issues/35#issuecomment-460242918):

>  the `netlink-packet` should only depend on `netlink-sys`, and only handle the raw netlink message. All the typed message should be moved to `netlink-packet-audit` or others, and we can chain the decoding process (`&[u8]` -> raw `NetlinkMessage` -> typed `AuditMessage`) with `Iterator` or `Stream`.

**Comment by flier** [comment]
I believe the core library should be as simple as possible, easy to maintain and rarely changed, because linux netlink protocol [rfc3549](https://tools.ietf.org/html/rfc3549) has stabled for years. 

If we handle all message type in one crate, we have to update it very frequently, it will cause the end user confused what happened and when the crate could be stable. If we could decouple the typed message from raw netlink message, the `netlink-sys`, `netlink-packet` and  `netlink-proto` will be stable very soon, and we just need update the **netlink-packet-audit** only.

Besides, the netlink protocol support the user defined protocol, we hard to support it with all-in-one `netlink-packet`.

- **netlink-sys** everything for OS binding
- **netlink-packet** handle the raw netlink message
- **netlink-proto** handle generic netlink protocol and connection (reassemble packet with sequence number)
- **netlink-tokio** handle  generic tokio stream/sink for async io
- **netlink-packet-XXX** handle the real netlink message
  - **netlink-packet-route**
  - **netlink-packet-audit**
  - **netlink-packet-sock-diag**
  - **netlink-packet-connector**
  - ...dozen of netlink message types
  - ...3rd party user defined message types

**Comment by little-dude** [comment]
> I believe the core library should be as simple as possible, easy to maintain and rarely changed, because linux netlink protocol rfc3549 has stabled for years.

Agree.

> If we could decouple the typed message from raw netlink message, the netlink-sys, netlink-packet and netlink-proto will be stable very soon, and we just need update the netlink-packet-audit only.

I'm sorry but I don't really understand this. If `netlink-packet` depends on a bunch of other crates like `netlink-packet-route`, `netlink-packet-audit`, etc. then the `Cargo.toml` will have something like:

```toml
[dependencies]
# a bunch of other dependencies
netlink-packet-audit = { path = "../netlink-packet-audit", version = "0.5" }
netlink-packet-sock-diag = { path = "../netlink-packet-sock-diag", version = "0.4" }
netlink-packet-route = { path = "../netlink-packet-route", version = "0.9" }
# etc
```

Then if `netlink-packet-route` is bumped to `0.10` for instance, we also need to bump the version of `netlink-packet`. So in the end, we still have to increment `netlink-packet`'s version as often as any of its dependencies changes version.

> - **netlink-proto** handle generic netlink protocol and connection (reassemble packet with sequence number)
> - **netlink-tokio** handle generic tokio stream/sink for async io

You're suggesting decoupling the protocol's state machine from the IO part right? I think that's a great idea, indeed.

**Comment by flier** [comment]
> > If we could decouple the typed message from raw netlink message, the netlink-sys, netlink-packet and netlink-proto will be stable very soon, and we just need update the netlink-packet-audit only.
> 
> I'm sorry but I don't really understand this. If `netlink-packet` depends on a bunch of other crates like `netlink-packet-route`, `netlink-packet-audit`, etc. then the `Cargo.toml` will have something like:
> 
That's our current problem, the `netlink-packet` should only depend on `netlink-sys`, and only handle the raw netlink message. All the typed message should be moved to `netlink-packet-audit` or others, and we can chain the decoding process (&[u8] -> raw NetlinkMessage -> typed AuditMessage) with `Iterator` or `Stream`.
> ```toml
> [dependencies]
> # a bunch of other dependencies
> netlink-packet-audit = { path = "../netlink-packet-audit", version = "0.5" }
> netlink-packet-sock-diag = { path = "../netlink-packet-sock-diag", version = "0.4" }
> netlink-packet-route = { path = "../netlink-packet-route", version = "0.9" }
> # etc
> ```
> 
> Then if `netlink-packet-route` is bumped to `0.10` for instance, we also need to bump the version of `netlink-packet`. So in the end, we still have to increment `netlink-packet`'s version as often as any of its dependencies changes version.
> 
> > * **netlink-proto** handle generic netlink protocol and connection (reassemble packet with sequence number)
> > * **netlink-tokio** handle generic tokio stream/sink for async io
> 
> You're suggesting decoupling the protocol's state machine from the IO part right? I hadn't thought of that and that seems like a great idea, indeed. I don't see any downside to doing that. Would you like to work on this? As I said I'm currently traveling and won't have much time to dedicate to coding for the next few weeks. Otherwise, we could just open a separate issue in case someone would like to work on it.

In fact, `tokio` use a similar design with [tokio-codec](https://tokio-rs.github.io/tokio/tokio_codec/index.html), all the netlink protocol related state machine could be extract to some helper like `framed`, and it could decode raw netlink message from socket or testing files. All typed message could be a `decoder`, we just need compose multi decoders.

**Comment by little-dude** [comment]
Aaah I understand know. That makes sense. Thanks for taking the time to explain in detail :)
