### ISSUE TITLE
abandon rtnetlink

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#40]
I'm not satisfied with `rtnetlink` API, and as shown in https://github.com/little-dude/netlink/pull/39, there are fundamental design issues when it comes to namespaces, which I have no idea how to fix.

**Comment by squeed** [comment]
It's not all bad :-). I think you've really hit on a good idea with the builder approach. Interfaces messages, in particular, are difficult to model in Rust. I'm not sure that [my approach](https://github.com/squeed/rust-netlink/blob/master/src/hl/iface/mod.rs#L28) is any more ergonomic.

I do think that single-threaded synchronous is the way to go, though. As you've correctly identified, switching namespaces is the one thing the library *has* to support - and without the hell that is dealing with namespaces in Go.

**Comment by little-dude** [comment]
Hello @squeed, sorry for not answering earlier, I stopped working on netlink for a few months.

> I do think that single-threaded synchronous is the way to go, though. As you've correctly identified, switching namespaces is the one thing the library has to support - and without the hell that is dealing with namespaces in Go.

Yeah I think so too. I am not familiar with go though. What kind of problems have they had wrt namespaces? Docker being built in Go, I would have assumed this was working pretty well.

> It's not all bad :-). I think you've really hit on a good idea with the builder approach. Interfaces messages, in particular, are difficult to model in Rust

Thanks for the kind words :) I kind of changed my mind about it being horrible anyway, because I think the upcoming async features in rust will make things a lot smoother. I guess I got frustrated a few months ago, hitting a wall and thinking about the time sunk into these crates ^^

Cheers

**Comment by little-dude** [comment]
Well I'm going to close this, as I said above, I don't think rtnetlink is _that_ bad anymore. I just requires some more work.
