### ISSUE TITLE
Support ip rule

### ISSUE THREAD

**Issue by mhristache** [little-dude/netlink#5]
Hi

I am looking for a netlink library in rust with support for `ip rule` manipulations. I checked the src code for this lib and it doesn't seem to support ip rules.

Do you plan to add such support?

Thanks

**Comment by areux** [comment]
Can you please start implementing RPDB aka ip-rule? I started working on improving the project but I don't quite know the netlink API. a shame rust still doesn't have a proper netlink library...

**Comment by little-dude** [comment]
> Can you please start implementing RPDB aka ip-rule?

I'll have more time to work on this crate this summer in July and August

> I started working on improving the project but I don't quite know the netlink API

Let me know if you have any question :)

> A shame rust still doesn't have a proper netlink library...

¯\\\_(ツ)\_/¯

**Comment by little-dude** [comment]
Support for this landed in `netlink-packet-route`. The next step would be to add this to `rtnetlink`.

**Comment by little-dude** [comment]
This has been implemented for a while now.
