### ISSUE TITLE
Implement FromRawFd for Socket in netlink-sys

### ISSUE THREAD

**Issue by ebkalderon** [little-dude/netlink#58]
## Motivation

There doesn't appear to be any way to create a new socket with `netlink_sys::Socket::new()` that conforms to this signature:

```
libc::socket(libc::PF_NETLINK, libc::SOCK_RAW | libc::SOCK_CLOEXEC, libc::NETLINK_ROUTE);
```

Apparently, the flags used in the constructor are hard-coded to `SOCK_DGRAM` with no option to specify something else. If `Socket` implemented [`FromRawFd`](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html), I could call `libc::socket()` directly, convert it to a `Socket`, and then use the API as normal.

## Alternatives

Another option could be to add another constructor besides `Socket::new()` with a higher-level API that allows you to specify flags without the user needing to resort to direct `libc` calls nor use of `unsafe`.

**Comment by ebkalderon** [comment]
The former option is extremely easy to do, while the latter might be more involved. With that said, I don't believe they are mutually exclusive. Having both options would be nice. I'm willing to open a pull request for the former right now, since it should be quite easy to implement.

**Comment by ebkalderon** [comment]
Feel free to re-open this issue if you decide to implement a dedicated safe API for specifying socket types!

**Comment by little-dude** [comment]
> Apparently, the flags used in the constructor are hard-coded to SOCK_DGRAM with no option to specify something else

I'm curious: why would you want `SOCK_RAW | ::SOCK_CLOEXEC` instead of `SOCK_DGRAM`, for a netlink socket? We could have `Socket::new()` take a `flags` argument instead of hardcoding `SOCK_DGRAM`, and maybe have `Socket::default()` which uses `SOCK_DGRAM`?

**Comment by ebkalderon** [comment]
I'm currently developing a user namespaces sandboxing crate which mimics [Bubblewrap](https://github.com/containers/bubblewrap), and there is [a socket call with those flags](https://github.com/containers/bubblewrap/blob/2105ff8ba4bb0680dc33543624d1642babbe01ce/network.c#L153) while setting up the loopback device for the sandboxed child process, which was cloned with a new network namespace (`CLONE_NEWNET`).

> We could have `Socket::new()` take a `flags` argument instead of hardcoding `SOCK_DGRAM`, and maybe have `Socket::default()` which uses `SOCK_DGRAM`?

Hmm, the user can't specify the desired `Protocol` via `Socket::default()`. What would we set the protocol to, in that case?

Perhaps we could have `Socket::new()` remain unchanged and then add a `Socket::with_flags()` constructor instead? Feel free to bikeshed the name. :smile:
