### ISSUE TITLE
How to get the IP addresses

### ISSUE THREAD

**Issue by mhristache** [little-dude/netlink#6]
Hi

I am looking for a way to retrieve the IP addresses for a link but could not find anything related to it in the `iproute2` crate so I guess I need to use `rtnetlink` which seems a bit more lower level.

Do you happen to have an example for this?

Thanks

**Comment by mhristache** [comment]
I am working on adding address support to iproute2. PR will (hopefully) come soon.

**Comment by little-dude** [comment]
Awesome :)

Sorry for not going back to you earlier. I currently lack time to work on this crate myself unfortunately, but I'll definitely review and merge a PR that adds addresses to iproute2.

I'm still planning a big refactor to add support for audit, but it's going to take a while to land :(
