### ISSUE TITLE
Looking for co-maintener(s)

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#68]
Hello,

I have had less time to work on my personal projects lately (it took me two weeks to get to review https://github.com/little-dude/netlink/pull/65 for example), so if anyone is interested in helping please let me know.

**Comment by JohnTitor** [comment]
@little-dude If you still need, I'm happy to help some work!

**Comment by hermantolim** [comment]
@little-dude count me in

**Comment by little-dude** [comment]
Hi @JohnTitor and @hermantolim, thanks a lot for offering to help! I sent you invites as collaborator so you should have write access to the repo already :) I can also add you on crates.io if you want, just let me know your user name.

Thank you again, I think I'm going to close this for now.
