### ISSUE TITLE
examples: dump_links does not compile

### ISSUE THREAD

**Issue by amalone-scwx** [little-dude/netlink#76]
Heads-up, there are some compile errors with dump_links example

steps:
 - `git clone git@github.com:little-dude/netlink`
 - `cargo build`
 - `cargo build --example dump_links`

It looks like it might be a sync example , but the crates default to async?

![image](https://user-images.githubusercontent.com/58046369/81317595-a947e280-9052-11ea-91ae-a5de71566cdb.png)

**Comment by wllenyj** [comment]
You need entry the netlink-packet-route dir, and `cargo build --example dump_links`. That 's ok.
