### ISSUE TITLE
Missing items for route query

### ISSUE THREAD

**Issue by cathay4t** [little-dude/netlink#94]
- [ ] `RTA_NH_ID`
- [ ] `netlink_packet_route::rtnl::nlas::route::MultiPath`
- [ ] `CacheInfo`, `Metric` should be parsed instead of showing as `Vec`.
- [ ] The `RTA_PREF` is u8, not a `Vec`.

**Comment by cathay4t** [comment]
I will take care of this issue. Just taking notes of my findings.

**Comment by little-dude** [comment]
I believe these have all been implemented in `netlink-packet-route` now. Multipath requires `rich-nlas` though.
